package com.xworkz.objects80;

public class Clip {
	 public String color="gray";
	 public String brand="trocess";
	 public int sizeInmm=20;
	 public String shape="squre";
	 public boolean isIthavingStones=true;
	 public String stoneType="pearl";
	 public String stoneShape="triangle";
     public String clipOccasion="marriage";
	 public String theme="classic";
	 public int numberOfStones=20;
	 public String clipMaterial="fiber";
	 public boolean isItNewArrivals=false;
	 public String platedMetalType="plastic";
	 public String clipMetal="steel";
	 public boolean isItHavingTeeth=false;
	 public boolean isItEasyToUse=false;
	 public boolean isItGripControl=true;
	 public boolean itsHavingFrench=true;
	 public boolean isItspringCover=false;
	 public boolean isItWaterproof=true;
	 public int numberOfTeeth=10;
	 public int numberOfPieces=20;
	 public int itemWeightIngram=20;
	 public String regionOfOrigin="India";
    public String packageContent="box";
	 
	 public String careInstructions="no chemicals";
	 public boolean isItSnagging=false;
	 public String modelName="crosset";
	 public String finish="glossy";
	 public boolean isItFoldable=false;
	 public int modelNo=128;
	 public int clipWeightInGrams=100;
	 public int cliplengthInInches=2;
	 public String manufacturer="bross company";
	 public boolean canBuyOnline=true;
	 public boolean GoodQuality=false;
	 public boolean isItHavingBun=false;
	 public String usage="tie hair";
	 public String closureMechanism="having socket";
	 public String maintenanceInstructions="wash before use";
	 public boolean  isWaterResistant=true;
	 public String functionality="flexible";
	 public String adjustability="";
	 public String texture="soft";
	 public  int durability=10;
	 public boolean hypoallergenic=false;
	 public boolean ecoFriendly=true;
	 public boolean isItwaterproof=true;
	 public boolean heatResistance=true;
	 public String stylingVersatility="any hairstyle";
	public boolean offlineAvailability=true;
	 public boolean isItJewellery=true;
	 public boolean isItHoldingHair=false;
	 public String affordability="not costly";
	 public boolean isItTrendy=false ;
	 public	String regionalCraftTechniques="hand made";
	 public String rivetDesign="aesthetic";
		public String rivetPlacement="in handle";
		public String rivetFinish="smooth";
		public String spineFinish="texture";
		public String tipDesign="sharp";
		public String tipShape="triangle";
		 public String handlePattern = "Grip lines";
        public String handleTexture = "glossy";
		    public boolean hasTravelCap = true;
		    public boolean isAntiBacterial = true;
        public String productFormulation = "Manual";
        public String retailerLocation="Delhi";
        public int quantityInStock=50;
        public boolean isShippable=true;
        public String shippingMethod="offline";
        public boolean havingAdditionalProperty=true;
        public String settingStyle="pong style";
        public String sizeUnit="in mm";
        public boolean isStackable=true;
        public boolean isEternity=true;
        public boolean isReSizable=true;
        public boolean hasInscription=true;
        public boolean isAntique=true;
        public boolean isModern=true;
        public int qualityRatingOutOfTen=7;
        public double marketValue=5.5d;


	 

}
