package com.xworkz.objects80;

public class Clock { 
		

    public String color="black";
    public String brandName="titan";
    public int weightInGramm=20;
    public String modelNumber="115D";
    public int price=20000;
    public boolean isWallClock=false;
    public boolean isWaterproof=true;
    public String frameMaterial="fiber";
      public boolean hasUSBPort=true;
    public boolean isCuckooClock=false;
    public boolean isPendulumClock=false;
    public boolean hasAlarm=true;
    public String shape="round";
    public String warranty="5 years";
    public boolean hasBattery=true;
    public int size=4;
    public boolean hasManufacturedate=true;
    public boolean isSmartClock=true;
    public String type="women wear";
    
    public String design= "floural";
    public boolean isPopularInIndia=true;
    public boolean isDigital=true;
    public boolean is24HourFormat=true;
    public boolean isPopularBrand=true;
    public boolean isOldestModel=true;
    public boolean usedAnywhere=false;
     public boolean hasSnoozeButton=false;
     public boolean isAtomicClock=false;
     public boolean hasTemperatureDisplay=true;
     public boolean isRadioCon=false;
    public String material="leather";
    public boolean isElectricPowered=true;
    public boolean isSolarPowered=false;
    public String numberOfHands="no hands"; 
    public boolean isNumberFormat=true;
    public boolean isModern=false;
    public boolean isAnalog=false;
    public boolean isHourlyChime=true;
    public String handsColour="no hands";
    public String numberColor="red";
   public boolean hasNightLight=true;
    public boolean hasChime=true;
    public boolean isBluetoothEnabled=false;
   public boolean hasDaylightSavingTime=true;
    public boolean hasMultipleTimezones=false;
    public boolean hasDateDisplay=false;
    public boolean isShockproof=true;
    public boolean isAntique=true;
    public int hours=5;
    public int minutes=2;
    public int seconds=50;
    public boolean hasDigitalDisplay=true;
    public boolean hasCountdownTimer=false;
    public boolean hasStopwatch=true;
    public boolean hasCalendar=false;
    public boolean hasBacklight=true;
    public boolean hasBluetoothSpeaker=false;
   public boolean hasVoiceControl=false;
    public boolean isDecorative=true;
    public boolean hasRemoteControlfalse;
  public boolean hasCustomizableFace=true;
    public boolean hasNFC=true;
    public int established =1969;
    public boolean hasWoodenFrame=false;
    public boolean hasMetallicFinish=true;
    public String founder="max" ;
    public boolean hasModernDesign=false;
    public boolean hasAlarmVolumeControl=false;
    public boolean hasAutoTimeSync=false;
    public boolean isWiFiConnected=true;
 public boolean hasLoudAlarm=false;
   public boolean hasSleepTimer=true;
    public String finish="glossy";
    public String glassShape="flat";
    public int noOfButtons=2;
    public String shapeOfbutton="round";
    public String strapType="bracelet";
    public boolean hasSnooze=false;
   public boolean hasWeightedBase=true;
    public String batteryType="silver oxide";
    public String manufacturedCoutry="US";
   

}
